### ISSUE TITLE
null response from currentUser.get() when openning website on mobile

### ISSUE THREAD

**Issue by robinodas** [vue-gapi/vue-gapi#126]
Hi team,

I get { Ca: null, xc: null } from gapi.auth2.getAuthInstance().currentUser.get() when openning website on mobile, though it's correct on PC.
Please help on check with it.

Cheers and thanks!

**Comment by robinodas** [comment]
More details for your reference:

OS: IOS 14
Browser: Safari/Chrome

**Comment by fmeyertoens** [comment]
You can call
```javascript
this.$gapi.getCurrentUser()
```
to get the current user object or are you trying to get it outside of a vue component?

**Comment by robinodas** [comment]
Try but also get { "Ca": null, "uc": null } only.

**Comment by namoscato** [comment]
Cleaning up some older issues, but feel free to re-open if you're still having problems.
