### ISSUE TITLE
Possibly unnecessary expiresAt function

### ISSUE THREAD

**Issue by fmeyertoens** [vue-gapi/vue-gapi#127]
We have a function that calculates the `expiresAt` Date from the `expires_in` seconds, althought according to the [docs](https://developers.google.com/identity/sign-in/web/reference#gapiauth2authresponse) we already get the `expires_at` timestamp with the AuthResponse. So can we just use this property?
https://github.com/vue-gapi/vue-gapi/blob/7e5498c92a362f6ff870a88b3a07653322e41f89/src/GoogleAuthService/utils.js#L25-L35

**Comment by namoscato** [comment]
Yeah, good call! I'm seeing that on inspection of `authResponse` as well.
