### ISSUE TITLE
Cannot find namespace 'gapi'.

### ISSUE THREAD

**Issue by dorklein** [vue-gapi/vue-gapi#158]
I installed the vue-gapi and when I run my vue-cli app with typescript it shows me:
49:26 Cannot find namespace 'gapi'.
    47 | 
    48 |     /** Ask to grant scopes from user. */
  > 49 |     grant: () => Promise<gapi.auth2.GoogleUser>
       |                          ^
    50 | 
    51 |     /** Signs out the current account from the application and clear session storage. */
    52 |     logout: () => Promise<void>
....

**Comment by namoscato** [comment]
@dorklein, what does your TSConfig look like? I'm guessing you need to add some packages to [`types`](https://www.typescriptlang.org/tsconfig#types) or something?

**Comment by namoscato** [comment]
Cleaning up some older issues, but feel free to re-open if you're still having problems.
