### ISSUE TITLE
[vue-gapi@next] Cannot find module 'vue-gap' 

### ISSUE THREAD

**Issue by dany-eudes** [vue-gapi/vue-gapi#159]
I'd like to use **vue-gapi** in a Quasar Framework 2.0.0-beta.9 project.

At the import statement I got a error message:  
`Cannot find module 'vue-gap' or its corresponding type declarations.ts(2307)`

It was just under the 'vue-gapi' declaration
`import VueGapi, { PluginOptions} from 'vue-gapi'`

````
Could not find a declaration file for module 'vue-gapi'. 'C:/path-to-my-app/node_modules/vue-gapi/dist/vue-gapi.common.js' implicitly has an 'any' type.

Try `npm i --save-dev @types/vue-gapi` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue-gapi';`ts(7016)

Any help will be appreciated.

**Comment by namoscato** [comment]
@dany-eudes, the type definitions don't exist yet (see https://github.com/vue-gapi/vue-gapi/pull/123)!

I should be able to add them this week.

**Comment by namoscato** [comment]
Actually, I had time to update them. Try installing `vue-gapi@next` again, and let me know if they work for you.

**Comment by dany-eudes** [comment]
Thank you very very much for your reply.
That's all fine now.

I was able to insert the plugin into a module in the quasar boot cycle and everything looks correct. I'll do some tests with Google Sheet API and if necessary I will come back with new questions.

Regards.
