### ISSUE TITLE
gmail api not supported?

### ISSUE THREAD

**Issue by alexvremja** [vue-gapi/vue-gapi#161]
need to use gmail api to verify the forwarding email filters that in plain js, can be accessed with this function:
`gapi.client.gmail.users.settings.filters.list()`

therefore I thought to access using `this.$gapi.client.gmail.users.settings.filters.list()`, but didn't exists:
actually I found gmail but in a "strange" position:
`this.$gapi.clientProvider.client.gapi.client.gmail`

I tried to use this object but it does not work.
Can suggest if gmail is accessable via vue-gapi, and if yes, how?
Thanks

**Comment by namoscato** [comment]
@alexvremja, you can get a reference to `gapi` via the promise-based [`getGapiClient`](https://vue-gapi.github.io/vue-gapi/reference/GoogleAuthService/_index.html#getgapiclient-%E2%87%92-promise-gapi) method, i.e.

```js
this.$gapi.getGapiClient().then((gapi) => {
    // gapi.client.gmail.users.settings.filters.list()...
});
```

**Comment by alexvremja** [comment]
Works!
great!
lost hours for nothing :-(
Thanks a lot!
