### ISSUE TITLE
No 'load' method

### ISSUE THREAD

**Issue by mirza-sync** [vue-gapi/vue-gapi#163]
Hi, I'm trying to implement playstore iframe from [android management API](https://developers.google.com/android/management/apps#step_2_render_the_iframe):

```
<script src="https://apis.google.com/js/api.js"></script>
<div id="container"></div>
<script>
  gapi.load('gapi.iframes', function() {
    var options = {
      'url': 'https://play.google.com/work/embedded/search?token=web_token&mode=SELECT',
      'where': document.getElementById('container'),
      'attributes': { style: 'width: 600px; height:1000px', scrolling: 'yes'}
    }

    var iframe = gapi.iframes.getContext().openChild(options);
  });
</script>
```

I'm using Vue 3 with Typescript and stumble up upon this vue-gapi library. Based on the code snippet, it requires me to use the `gapi.load` and `gapi.iframes` method. However those methods are not available in this library or in its documentation. I already have the `iframeUrl` and `web token`. Just need a way to implement the iframe on frontend. Can someone help me on this?

Thanks.

**Comment by fmeyertoens** [comment]
When using this library with Vue3 be sure to use the `vue-gapi@next` release tag.
The purpose of this library is to abstract the initialization of the gapi library provided by Google and give you easy access to it in Vue components without having to worry about script tags, global objects and user session storage. To enable that, the most important functions for authentication are exposed with a nice API.
This library does not populate the `gapi` object with the methods you see like `load` and `iframes` though. The gapi library already does that. You can access the `gapi` object (and the methods on it) by calling `this.$gapi.getGapiClient().then(gapi => ...` in your Vue components which returns a Promise of the object. ([Docs](https://vue-gapi.github.io/vue-gapi/reference/GoogleAuthService/_index.html#new-googleauthservice)).
You can find the types for the android management API here: https://www.npmjs.com/package/@maxim_mazurok/gapi.client.androidmanagement.

**Comment by mirza-sync** [comment]
Okay it works! Thanks for the guidance.
