### ISSUE TITLE
How do you use it with composition api?

### ISSUE THREAD

**Issue by ArvidAnderson** [vue-gapi/vue-gapi#203]
As this.$gapi dosen't work in the composition api, how are you supposed to use it?

I wanna continue working in the setup function

**Comment by namoscato** [comment]
Yeah, there is no support for the Composition API at the moment, but you should still be able to reference [`GoogleAuthService` methods](https://vue-gapi.github.io/vue-gapi/reference/GoogleAuthService/_index.html#googleauthservice) via `this.$gapi`. If not, can you provide some more context on your use case?

**Comment by ArvidAnderson** [comment]
I'm mainly using the composition api for my project, i found a soulution with works after some time searching..

`import { getCurrentInstance } from 'vue'

const app = getCurrentInstance()
const gapi = app.appContext.config.globalProperties.$gapi

`

**Comment by skirtles-code** [comment]
@namoscato There is no `this` reference inside `setup`. The way most libraries handle this is to use `provide`/`inject` instead, with the plugin providing the value on the app. Most libraries also supply a wrapper for the `inject` call, something like `useGapi()`, that can be called from within `setup`.

**Comment by namoscato** [comment]
Gotcha, yeah this would be good to support for sure.

**Comment by rowellx68** [comment]
> @namoscato There is no `this` reference inside `setup`. The way most libraries handle this is to use `provide`/`inject` instead, with the plugin providing the value on the app. Most libraries also supply a wrapper for the `inject` call, something like `useGapi()`, that can be called from within `setup`.

Based on @skirtles-code's reply, this is my current workaround

**main.ts**
```ts
app.use(VueGapi, options)
app.provide('gapi', app.config.globalProperties.$gapi)
```

**google-api-helper.ts**

```ts
import { VueGapi } from 'vue-gapi'
import { inject } from 'vue'

export const useGapi = (): VueGapi => {
  return inject('gapi')!
}
```

**Login.vue**
```vue
<script setup lang="ts">
import { useGapi } from 'utils/google-api-helper'

const gapi = useGapi()

// rest of the code
</script>
```

**Comment by namoscato** [comment]
@ArvidAnderson, @skirtles-code, @rowellx68 – `v2.1.0-beta.0` should add support for Composition API dependency injection via a `useGapi` wrapper. Would one of you mind giving this a try?
