### ISSUE TITLE
add typing for calendar

### ISSUE THREAD

**Issue by zynth17** [vue-gapi/vue-gapi#253]
is it possible to add the calendar instance types?

**Comment by namoscato** [comment]
@zynth17, not in this library, but you should be able to add them from DefinitelyTyped (i.e. [`@types/gapi.client.calendar`](https://www.npmjs.com/package/@types/gapi.client.calendar)).

**Comment by namoscato** [comment]
Cleaning up some older issues, but feel free to re-open if you're still having problems.
