### ISSUE TITLE
Google Sign-in platform deprecated, use GIS ?

### ISSUE THREAD

**Issue by kpoman** [vue-gapi/vue-gapi#315]
Hello,

I am using the lib, working, but cant login or do whatever as I get this on the console:

```
{
    "error": "idpiframe_initialization_failed",
    "details": "You have created a new client application that uses libraries for user authentication or authorization that will soon be deprecated. New clients must use the new libraries instead; existing clients must also migrate before these libraries are deprecated. See the [Migration Guide](https://developers.google.com/identity/gsi/web/guides/gis-migration) for more information."
}
```
They seem to say the method (with init etc.) used by vue-gapi is deprecated and should migrate to GIS ? Is that real ????
Thank you

**Comment by namoscato** [comment]
Yeah, thanks for flagging, @kpoman. Per [this blog](https://developers.googleblog.com/2022/03/gis-jsweb-authz-migration.html):

> On March 31, 2023 we will fully retire the Google Sign-In JavaScript Platform Library and would like to remind you to check if this affects your web application, and if necessary, to plan for a migration.
>
> Beginning April 30th, 2022 new applications must use the Google Identity Services library, existing apps may continue using the Platform Library until the deprecation date.

We'll plan to make updates to this library in the next major version (v3), as I imagine there will be some breaking changes.

**Comment by prem-jeet** [comment]
I this is the case, then how can we use this library in our current project ?

**Comment by Aubynj** [comment]
Any update for this library to use the new Google Identity Services library?

**Comment by RichardJECooke** [comment]
Yes, this project should probably be combined with the Vue GSI (https://vue3-google-signin.syetalabs.io/) project. They're highly interrelated.

**Comment by namoscato** [comment]
Thanks, @RichardJECooke!

[v2.1.2](https://github.com/vue-gapi/vue-gapi/releases/tag/v2.1.2) adds a [deprecation notice](https://github.com/vue-gapi/vue-gapi#%EF%B8%8F-deprecation) pointing to that project, which we would encourage you to use.
