### ISSUE TITLE
Does this always load the latest gapi version?

### ISSUE THREAD

**Issue by BenJackGill** [vue-gapi/vue-gapi#331]
I'm wondering if this uses a static version of gapi or does it always grab and use the most recent version?

**Comment by namoscato** [comment]
@BenJackGill, it loads the latest / only version:

https://github.com/vue-gapi/vue-gapi/blob/7ce39fc613257a42f5cb58478408a57c34b581f2/src/GapiClientProvider/utils.js#L8
