### ISSUE TITLE
Library will be deprecated?

### ISSUE THREAD

**Issue by lucianobosco** [vue-gapi/vue-gapi#376]
I'm new on Google API development.
I'm not sure to understand if this library will be deprecated or not in 2023. 
The Google Sign-In JavaScript Platform Library is a dependency of this library?

**Comment by namoscato** [comment]
Assuming you're creating a new application, you'll want to use the recommended [Vue3 Google Sign-in](https://vue3-google-signin.syetalabs.io/). This library will not support Google Identity Services, and you can read more about Google's change in [this blog](https://developers.googleblog.com/2022/03/gis-jsweb-authz-migration.html).
