### ISSUE TITLE
will the plugin work with the old one google sign method after March 31 ? 

### ISSUE THREAD

**Issue by dmytrodemchenko** [vue-gapi/vue-gapi#379]

**Comment by namoscato** [comment]
[Per Google](https://developers.googleblog.com/2022/03/gis-jsweb-authz-migration.html), they "will fully retire the Google Sign-In JavaScript Platform Library" on March 31, 2023, so you will likely need to migrate to [Vue3 Google Sign-in](https://vue3-google-signin.syetalabs.io/).

**Comment by dmytrodemchenko** [comment]
Thanks a lot for your answer!
