### ISSUE TITLE
Add scope authorization check

### ISSUE THREAD

**Issue by namoscato** [vue-gapi/vue-gapi#41]
It would be nice to easily determine whether or not the user has granted access to the specified scopes post-login via [`GoogleUser.hasGrantedScopes`](https://developers.google.com/identity/sign-in/web/reference#googleuserhasgrantedscopesscopes). Perhaps this boolean could be passed to the login callback / resolve?

**Comment by cedpoilly** [comment]
@namoscato Good idea. Approved. Please provide a PR ✌🏼
