### ISSUE TITLE
$gapi.isSignedIn return a pending promise instead of boolean

### ISSUE THREAD

**Issue by asiz15** [vue-gapi/vue-gapi#53]
![Screen Shot 2020-06-22 at 7 59 33 PM](https://user-images.githubusercontent.com/13662081/85346271-fe389e80-b4c2-11ea-8847-85ab67b00cd6.png)

**Comment by cedpoilly** [comment]
@asiz15 Thanks for pointing this out.

I've checked the code & check the documentation for GAPI: it should return a boolean value directly.

Thus, kindly show me the code on your side, or provide a small replication so that I can debug. 🙂

Cheers!

**Comment by apgapg** [comment]
```
computed: {
      isSignedIn() {
        return this.$isSignedIn()
      },
    },
```

this return Promise instead of bool

**Comment by cedpoilly** [comment]
@apgapg Sorry for the confusion. The current implementation returns a promise.
Reason: it is calling the plugin itself to access `gapi`.

You will need to handle it in an async way: either with the Promise API or with 'async..await'.

Let me know if that helps.

**Comment by idrys** [comment]
`computed: {
      isSignedIn() {
        Promise.resolve(
          this.$isSignedIn().then( (data) =>{
            this.authorized = data
          })
        )
      },
    },`

**Comment by namoscato** [comment]
[`isSignedIn` documentation](https://vue-gapi.github.io/vue-gapi/GoogleAuthService.html#isSignedIn) has been updated and is accessible as follows in [v1.0](https://github.com/vue-gapi/vue-gapi/releases/tag/v1.0.0):

```js
computed: {
  isSignedIn() {
    return this.$gapi.isSignedIn().then((authorized) => {
      this.authorized = authorized
    })
  },
},
```

Note that `this.$isSignedIn()` has been deprecated and is now removed.
