### ISSUE TITLE
Missing required authentication credential

### ISSUE THREAD

**Issue by eparadise** [vue-gapi/vue-gapi#54]
Hi,

Thank you for this library! I am trying to create a form that, when submitted, writes data to a Google sheet. I used vue-gapi and configured it as specified, but when I click my submit button I get the following error: "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential." 
This is the code that sets up the API:
```
import VueGAPI from 'vue-gapi'
const apiConfig = {
  apiKey: 'MY_KEY',
  clientId: 'MY_ID',
  discoveryDocs: ['https://sheets.googleapis.com/$discovery/rest?version=v4'],
  scope: 'https://www.googleapis.com/auth/spreadsheets'
}

Vue.use(VueGAPI, apiConfig)
```
This is the code that tries to write to the sheet:
```
this.$getGapiClient().then((gapi) => {
          const params = {
            spreadsheetId: '1IZfst0hsjboYwn8KZe-oAbQj8LBPZDBKmBHnoQA-nsE',
            range: 'Sheet1',
            valueInputOption: 'RAW',
            insertDataOption: 'INSERT_ROWS'
          }
          const valueRangeBody = {
            majordimension: 'ROWS',
            values: ['testing', 'testing', 'testing', 'testing', 'testing', 'testing', 'testing', 'testing']
          }
          let request = gapi.client.sheets.spreadsheets.values.append(params, valueRangeBody)
          request.then(
            function (response) {
              console.log(response.result)
              alert(
                'The form has been submitted. Thank you for your help updating the entry!'
              )
              this.selected = []
            },
            function (reason) {
              console.error('error: ' + reason.result.error.message)
            }
          )
        })
```
I've been Googling for a while with no luck, so any ideas would really be appreciated!

**Comment by cedpoilly** [comment]
@eparadise 

Glad to know your using VueGAPI, thanks!

For the issue, I'll first ask: which **version** are you currently using?

Also, are the values properly stored in **localStorage**?

**Comment by namoscato** [comment]
@eparadise, I'm not sure if you're still experiencing this issue, but I'm guessing the user needed to [login](https://vue-gapi.github.io/vue-gapi/GoogleAuthService.html#login) first.

I'm going to close this out given its age but happy to help / re-open if you're still experiencing issues.
