### ISSUE TITLE
Add TypeScript type definitions

### ISSUE THREAD

**Issue by namoscato** [vue-gapi/vue-gapi#59]
We should be able to start from [something like this](https://github.com/namoscato/google-photos-vue/blob/138243a143e9a220526a24af1a1046e61d406ac1/src/types/gapi.d.ts).

**Comment by fmeyertoens** [comment]
> 
> 
> There are already type packages for [gapi ](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/gapi)and [gapi.auth2](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/gapi.auth2) that we can use like [ng-gapi](https://github.com/rubenCodeforges/ng-gapi) for angular does it.

_Originally posted by @fmeyertoens in https://github.com/cedpoilly/vue-gapi/issues/6#issuecomment-532272081_

We tried to do this last year. Unfortunately I didn't have the time back then but I'm still interested in getting this to work.

**Comment by namoscato** [comment]
@fmeyertoens, nice! Yeah, that makes sense to me.

I'm planning to focus on some internal build / CI stuff first but also happy to help out with this.

**Comment by cedpoilly** [comment]
@fmeyertoens happy to have a PR from you for the same 🙂
