### ISSUE TITLE
this.$gapi.isAuthenticated() is returning true even after logout

### ISSUE THREAD

**Issue by apgapg** [vue-gapi/vue-gapi#61]
```
 onDriveLogoutClick: function() {
      this.$gapi.getGapiClient().then(gapi => {
        gapi.auth2
          .getAuthInstance()
          .signOut()
          .then(() => {
            this.gDriveAuthenticated = false;
            console.log("Drive logout successful");
          })
          .catch(err => {
            // eslint-disable-next-line no-console
            console.error("Login call failed: %s", err.message);
          });
      });
    }
```

Even after logout(above code) 
`console.log("isAuth:" + this.$gapi.isAuthenticated());`

this is giving **true**

**Comment by namoscato** [comment]
@apgapg, did you try using the `logout()` method? i.e.

```js
onDriveLogoutClick: function() {
  this.$gapi.logout().then(() => {
    this.gDriveAuthenticated = false;
    console.log("Drive logout successful");
  })
  .catch(err => {
    // eslint-disable-next-line no-console
    console.error("Login call failed: %s", err.message);
  });
}
```

This should effectively invoke `gapi.auth2.getAuthInstance().signOut()` as you are doing but also clears the relevant local storage items which affect `isAuthenticated()`.

**Comment by apgapg** [comment]
Okay this means this lib also stores its own local data to check for login status?
I thought the two methods are same ie `this.$gapi.logout()` & `gapi.auth2.getAuthInstance().signOut()`
Can you please update README? It gives the methods are deprecated.

**Comment by cedpoilly** [comment]
@apgapg Thanks. I will update the documentation. Give us some time 🙂

**Comment by deCodeIt** [comment]
Perhaps it's better to check for `isSignedIn` within `isAuthenticated` method?

**Comment by namoscato** [comment]
I created https://github.com/vue-gapi/vue-gapi/issues/129 to handle the documentation update and am going to close this out.
