### ISSUE TITLE
Support for Vue 3

### ISSUE THREAD

**Issue by cnguyen-de** [vue-gapi/vue-gapi#73]
Since Vue 3 is now in RC, would it be possible to support Vue 3?

**Comment by namoscato** [comment]
@cnguyen-de, thanks for your patience on this!

We're currently working towards releasing v1.0 of this plugin. Feel free to follow along in https://github.com/vue-gapi/vue-gapi/issues/105 and/or leave feedback.

I'm leaning towards supporting Vue 3 in a v2.0 – which would be a fast-follow. Hopefully all of that dust will settle over the next ~month.

**Comment by namoscato** [comment]
@cnguyen-de, a Vue 3-compatible version of this plugin is in beta and available via `vue-gapi@next`.

`$gapi` is available as a [global property](https://v3.vuejs.org/api/application-config.html#globalproperties) and accessible via `this.$gapi` inside the application, analogous to the Vue v2.x usage. We might add some additional features around the new Composition API at some point and are open to feedback!

**Comment by cnguyen-de** [comment]
@namoscato thanks for the update, will check it out asap. Will report back if I encounter any issues.

**Comment by StavrosFerkadis** [comment]
Would love to see an example in Vue 3

**Comment by namoscato** [comment]
@StavrosFerkadis, the plugin is pretty similar at the moment in Vue 3. You can view [updated examples here](https://github.com/vue-gapi/vue-gapi/pull/123/files?short_path=642c10b#diff-642c10b720d07ebba25e364603ad763fbc6e4542cb4b894dd6538821ee76c4af).
