### ISSUE TITLE
grantOfflineAccess

### ISSUE THREAD

**Issue by altoP** [vue-gapi/vue-gapi#76]
is there a way to call grantOfflineAccess to get the authorization code?

**Comment by namoscato** [comment]
@altoP, it doesn't look like we're returning the authorization code at the moment, but you should be able to retrieve it via [`getOfflineAccessCode()`](https://vue-gapi.github.io/vue-gapi/GoogleAuthService.html#getOfflineAccessCode), i.e.

```js
this.$gapi.grantOfflineAccess().then(() => {
   console.log(this.$gapi.getOfflineAccessCode());
});
```

**Comment by namoscato** [comment]
@altoP, [v1.0](https://github.com/vue-gapi/vue-gapi/releases/tag/v1.0.0) introduces several improvements on this front:

1. `grantOfflineAccess` is now resolved with the authorization code
2. The authorization code is now persisted in local storage and can be retrieved via [`getOfflineAccessCode`](https://vue-gapi.github.io/vue-gapi/GoogleAuthService.html#getOfflineAccessCode)
